//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public string fullName { get; set; }
        public string patientId { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string telephone { get; set; }
        public string mobilePhone { get; set; }
    
        public virtual coronaVirusDetail coronaVirusDetail { get; set; }
    }
}
